version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@1.4.0
jobs:
  test_client:
    description: Run Tests
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - gcp-gke/install
      # Build Image and Test
      - run:
          name: Build Client Image
          command: |
            docker build -t austinmutschler/multi-client-test -f ./client/Dockerfile .
      # Run Tests
      - run:
          name: Run Client Tests
          command: |
            docker run -e CI=true austinmutschler/multi-client-test npm run test
  deploy_production:
    description: Deploy application to Google Kubernetes Engine
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - gcp-gke/install
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: multi-cluster
      #- gcp-gke/rollout-image:
      #    cluster: multi-cluster
      #    container: 
      #    deployment: 
      #    image: 

      - run:
          name: Rollout K8s
          command: |
            echo Hello World!

workflows:
  test_build_deploy:
    jobs:
      - test_client
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy_production:
          requires:
            - test
            - hold
          filters:
            branches:
              only:
                - master
